### ISSUE TITLE
Recover all the old Camba.tv Blog Posts

### ISSUE THREAD

**Issue by marcoherbst** [Cambatv/camba.tv#14]
Until about 4 or 5 months ago, we had a few hundred old camba blog posts in our DB.

During the clean up and as part of our fear of the malware, we deleted all of these.

I am hoping you might, in a safe environment, recover the old DB, extract the bits we know are safe - the html and the jpegs and get them reposted with the correct dates on to our current site.

This will be a fiddly task and we certainly dont want to risk bringing the malware back to life, but it would be great to be able to do it.

**Comment by marcoherbst** [comment]
@affan00  ... do you have any thoughts on this. What is the oldest backup to which you have access?

**Comment by affan00** [comment]
I have the oldest backup of date 01-sep-2016.

M. Affan Qureshi
Cell No. : +923136007500
Skype: affan_ani

**Comment by affan00** [comment]
still we have no oldest backups for recover old blog posts.
