### ISSUE TITLE
Move to Jekyll / Github Pages

### ISSUE THREAD

**Issue by marcoherbst** [Cambatv/camba.tv#2]
@muneeb2542 , you could handle this? 

Do it nice and slowly, consider backups, DNS etc.

Also, cautiously look at the codebase to see if you spot anything suspicious, we have had problems here. Asim lost a lot of files from a virus. 

At some point we'll put an SSL cert on this too. (or relocate /pay to evercam.io)

M

**Comment by marcoherbst** [comment]
From @azharmalik3 : 

1) Leave current camba.tv and database as it is.
2) Create new website on AWS and configure wordpress with new database. 
3) Install fresh copy of innovado theme and then add theme changes and pages content. 
4) Add captcha in contact forms.
5) Enable auto backup.


Alternative 2: 
Move to Jekyll ?

**Comment by azharmalik3** [comment]
Move to Jekyll is good idea and good task for Affan.

Note: Before start camba.tv in Jekyll we must verify that easy to
integrate *Make
a Payment* and *Contact Form*.

On Tue, Oct 13, 2015 at 2:16 PM, Marco Herbst <notifications@github.com>
wrote:

> From @azharmalik3 <https://github.com/azharmalik3> :
>
> 1) Leave current camba.tv and database as it is.
> 2) Create new website on AWS and configure wordpress with new database.
> 3) Install fresh copy of innovado theme and then add theme changes and
> pages content.
> 4) Add captcha in contact forms.
> 5) Enable auto backup.
>
> Alternative 2:
> Move to Jekyll ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cambatv/camba.tv/issues/2#issuecomment-147658637>.
>



-- 
Azhar Malik
Senior Software Engineer
Evercam.io
Phone: +92 322 624 8204
Skype: azharmalik3
Email: http://www.evercam.io <http://www.evercam.io/team>

**Comment by marcoherbst** [comment]
Contact Form - 100% , there's heaps of ways to solve this (hosted forms)
e.g. https://formspree.io/

Make a Payment - This is also solveable. At worst, we'd direct people to a
page hosted on Evercam.

So, those issues are not blockers. My concern was more that we don't get
the benefits of Wordpress Themes. You think that's not a problem?

M



On 13 October 2015 at 10:28, Azhar Malik <notifications@github.com> wrote:

> Move to Jekyll is good idea and good task for Affan.
>
> Note: Before start camba.tv in Jekyll we must verify that easy to
> integrate *Make
> a Payment* and *Contact Form*.
>
> On Tue, Oct 13, 2015 at 2:16 PM, Marco Herbst <notifications@github.com>
> wrote:
>
> > From @azharmalik3 <https://github.com/azharmalik3> :
> >
> > 1) Leave current camba.tv and database as it is.
> > 2) Create new website on AWS and configure wordpress with new database.
> > 3) Install fresh copy of innovado theme and then add theme changes and
> > pages content.
> > 4) Add captcha in contact forms.
> > 5) Enable auto backup.
> >
> > Alternative 2:
> > Move to Jekyll ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Cambatv/camba.tv/issues/2#issuecomment-147658637>.
> >
>
>
>
> --
> Azhar Malik
> Senior Software Engineer
> Evercam.io
> Phone: +92 322 624 8204
> Skype: azharmalik3
> Email: http://www.evercam.io <http://www.evercam.io/team>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cambatv/camba.tv/issues/2#issuecomment-147661702>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst

**Comment by azharmalik3** [comment]
No that's not a problem. We can easily get benefits from wordpress theme.

On Tue, Oct 13, 2015 at 3:06 PM, Marco Herbst <notifications@github.com>
wrote:

> Contact Form - 100% , there's heaps of ways to solve this (hosted forms)
> e.g. https://formspree.io/
>
> Make a Payment - This is also solveable. At worst, we'd direct people to a
> page hosted on Evercam.
>
> So, those issues are not blockers. My concern was more that we don't get
> the benefits of Wordpress Themes. You think that's not a problem?
>
> M
>
>
>
> On 13 October 2015 at 10:28, Azhar Malik <notifications@github.com> wrote:
>
> > Move to Jekyll is good idea and good task for Affan.
> >
> > Note: Before start camba.tv in Jekyll we must verify that easy to
> > integrate *Make
> > a Payment* and *Contact Form*.
> >
> > On Tue, Oct 13, 2015 at 2:16 PM, Marco Herbst <notifications@github.com>
> > wrote:
> >
> > > From @azharmalik3 <https://github.com/azharmalik3> :
> > >
> > > 1) Leave current camba.tv and database as it is.
> > > 2) Create new website on AWS and configure wordpress with new database.
> > > 3) Install fresh copy of innovado theme and then add theme changes and
> > > pages content.
> > > 4) Add captcha in contact forms.
> > > 5) Enable auto backup.
> > >
> > > Alternative 2:
> > > Move to Jekyll ?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/Cambatv/camba.tv/issues/2#issuecomment-147658637>.
> > >
> >
> >
> >
> > --
> > Azhar Malik
> > Senior Software Engineer
> > Evercam.io
> > Phone: +92 322 624 8204
> > Skype: azharmalik3
> > Email: http://www.evercam.io <http://www.evercam.io/team>
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/Cambatv/camba.tv/issues/2#issuecomment-147661702>.
> >
>
>
>
> --
> Marco Herbst
> *Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
> Mobile: +353 86 196 0451
> Skype: marco.a.herbst
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cambatv/camba.tv/issues/2#issuecomment-147669494>.
>



-- 
Azhar Malik
Senior Software Engineer
Evercam.io
Phone: +92 322 624 8204
Skype: azharmalik3
Email: http://www.evercam.io <http://www.evercam.io/team>

**Comment by marcoherbst** [comment]
Sounds like a deal :)

Stripe: https://json.expert/flatmarket/

M

**Comment by marcoherbst** [comment]
Happy with WP. Closing.
