### ISSUE TITLE
Couple of changes to camba.tv

### ISSUE THREAD

**Issue by rossom** [Cambatv/camba.tv#3]
Hi Asim

Can we please get these changes made to the camba website over the coming days?

Any probs - just shout!

Thanks
Ross

![slide2](https://cloud.githubusercontent.com/assets/4725787/10519149/705b4de4-735c-11e5-8783-562fe48b886f.JPG)
![slide3](https://cloud.githubusercontent.com/assets/4725787/10519150/705b7300-735c-11e5-8d10-26cffba7ece2.JPG)
![slide1](https://cloud.githubusercontent.com/assets/4725787/10519151/705b807a-735c-11e5-993a-ab45de6f9986.JPG)

**Comment by asimism** [comment]
Done all those changes.
