### ISSUE TITLE
changes to cloud.camba.tv

### ISSUE THREAD

**Issue by rossom** [Cambatv/camba.tv#4]
Hi

This page is outdated and should be deleted except it performs well on SEO. 

For that reason i propose replacing the content with the attached. 

Lets discuss.

R.

![servers](https://cloud.githubusercontent.com/assets/4725787/10520922/d604d4fa-7364-11e5-8be7-8a493b5b1439.jpg)
![changes to cloud dot camba page](https://cloud.githubusercontent.com/assets/4725787/10520923/d606b68a-7364-11e5-81ba-83cda07846a3.jpg)

**Comment by rossom** [comment]
Marco - can you provide feedback or assign this to Asim if it's ok with you?

**Comment by marcoherbst** [comment]
This is an Evercam task, closing it.
