### ISSUE TITLE
Including string for google ads in contact form on camba.tv

### ISSUE THREAD

**Issue by rossom** [Cambatv/camba.tv#5]
Hi Asim,

We wish to track people who come to the site via Google advertising. 

Reason: so we can establish which of our campaigns are performing well.

As part of this I have appended a string on to the end of each url we link to from google adwords (see below)

When people come to the website I want this string to be saved (by cookie?) on the site.

When a user fills in the form, I want this string to be included in the mail we receive.
So we'll get name, email address, phone number, message etc - AND something like aff=clicks_CCTV_cctv_never_looked_so_good

Timing: This should only save the persons most recent "aff=" (i.e. it should overwrite the older one if I've clicked on more than two ads)

There may be more on this, but for now I am keen to get this live when you're next working on the camba site.

Cheers

Ross.

Campaign: Camba.tv website clicks

- Ad Group: CCTV 
www.camba.tv?aff=clicks_CCTV_cctv_and_security_systems 
www.camba.tv?aff=clicks_CCTV_cctv_never_looked_so_good
www.camba.tv?aff=clicks_CCTV_upgrade_your_cctv_system
www.camba.tv?aff=clicks_CCTV_cctv_systems_dublin

- Ad Group: Security Systems
www.camba.tv?aff=clicks_SECURITYSYSTEMS_cctv_alarms_and_access
www.camba.tv?aff=clicks_SECURITYSYSTEMS_cctv_and_security_systems 

- Ad Group: Security
www.camba.tv?aff=clicks_SECURITY_cctv_and_security_systems 
www.camba.tv?aff=clicks_SECURITY_cctv_never_looked_so_good
www.camba.tv?aff=clicks_SECURITY_upgrade_your_cctv_system
www.camba.tv?aff=clicks_SECURITY_cctv_alarms_and_access

Campaign: Remarketing

www.camba.tv?aff=remarketing_20150923
www.camba.tv?aff=remarketing_20151001
www.camba.tv?aff=remarketing_cctv_never_looked_so_good

Campaign: Vendor & Competitors 

- Ad Group: Vendors
www.camba.tv?aff=ven_cctv_and_security_systems
www.camba.tv?aff=ven_cctv_never_looked_so_good
www.camba.tv?aff=ven_cctv_alarms_and_access
www.camba.tv/services/#SystemUpgrades?aff=ven_upgrade_your_cctv_system

- Ad Group: Competitors
www.camba.tv?aff=com_cctv_and_security_systems
www.camba.tv?aff=com_cctv_never_looked_so_good
www.camba.tv?aff=com_cctv_alarms_and_access
www.camba.tv/services/#SystemUpgrades?aff=com_upgrade_your_cctv_system

**Comment by marcoherbst** [comment]
@rossom ... I'm assuming your recent email to @affan00 supercedes this ticket?

**Comment by rossom** [comment]
@marcoherbst Yes.
