### ISSUE TITLE
alterations to forms on camba.tv

### ISSUE THREAD

**Issue by rossom** [Cambatv/camba.tv#6]
Hi

Firstly, apologies for flip flopping on this. We have recently had some people fill the form in on our site with just their name (and no contact details) - which is a wasted lead.

SO we need to make at least one of the contact fields Phone or Email compulsory.

If they fill neither in, I'd like them to get a pop up saying

"We require either your phone number or email address to contact you"

If they have entered an email address in but it's an odd format, such as missing an "@" symbol, or not having a domain at the end, ideally they would get a warning stating this. 

Similarly if they have filled a phone number in but it contains less than 7 digits, or characters outside of "0-9 + () -" then they should get a warning stating this.

Does that all sound ok? Happy to discuss further at your convenience - would possibly make sense to do this with the other work on site over the coming days?

Cheers

Ross.

**Comment by alinerotta** [comment]
@asimism  just wondering when you might get to look at this ?

Aline

**Comment by asimism** [comment]
Hi Aline
will get this sorted by tomorrow.
Regards
Asim

**Comment by alinerotta** [comment]
Thanks @asimism !

**Comment by alinerotta** [comment]
Hi @asimism whenever you have time this week can you hale a look at this ? People are still able to submit the form without filling any information.
Regards, 

Aline.
