### ISSUE TITLE
Configure dailybackups for this site.

### ISSUE THREAD

**Issue by marcoherbst** [Cambatv/camba.tv#8]
Find a way that suits you.

https://github.com/colinbjohnson/aws-missing-tools if you like ?
m

**Comment by muneeb2542** [comment]
ok  so i have found a way to get daily backups and its actually a plugin.
So i want to know now is that where should the backup be saved, in a local machine or on the cloud??

**Comment by marcoherbst** [comment]
s3

On 29 October 2015 at 13:00, muneeb <notifications@github.com> wrote:

> ok so i have found a way to get daily backups and its actually a plugin.
> So i want to know now is that where should the backup be saved, in a local
> machine or on the cloud??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Cambatv/camba.tv/issues/8#issuecomment-152173194>.
>



-- 
Marco Herbst
*Evercam.io <http://www.evercam.io/>* - Cameras Unleashed
Mobile: +353 86 196 0451
Skype: marco.a.herbst
